import React from 'react';
import { useNavigate } from 'react-router-dom';
import useClaimStore from '../store/useClaimStore';
import { ConfidenceBadge } from '../components/result/ConfidenceBadge';

const AuditLogPage: React.FC = () => {
  const { auditHistory, loadClaimResult } = useClaimStore();
  const navigate = useNavigate();

  const handleReplay = (result: any) => {
    loadClaimResult(result);
    navigate('/claims');
  };

  return (
    <div className="flex-1 overflow-y-auto bg-[#F9FAFB] p-8">
      <div className="max-w-6xl mx-auto">
        <div className="mb-8">
          <h1 className="text-2xl font-black text-gray-900 tracking-tight">Audit Trail History</h1>
          <p className="text-sm text-gray-500 font-medium">Review and verify every decision generated by the AI pipeline</p>
        </div>

        {auditHistory.length === 0 ? (
          <div className="bg-white border border-dashed border-gray-300 rounded-xl p-16 flex flex-col items-center justify-center text-center">
            <div className="w-16 h-16 bg-gray-50 rounded-full flex items-center justify-center mb-4">
              <span className="material-symbols-outlined text-gray-300 text-[32px]">folder_open</span>
            </div>
            <h3 className="text-lg font-bold text-gray-900">No audits found</h3>
            <p className="text-sm text-gray-400 max-w-xs mt-1">Processed claims will appear here automatically for session-based review.</p>
          </div>
        ) : (
          <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-200">
                  <th className="px-6 py-4 text-[11px] font-black uppercase tracking-wider text-gray-400">Claim ID</th>
                  <th className="px-6 py-4 text-[11px] font-black uppercase tracking-wider text-gray-400">Verdict</th>
                  <th className="px-6 py-4 text-[11px] font-black uppercase tracking-wider text-gray-400">Confidence</th>
                  <th className="px-6 py-4 text-[11px] font-black uppercase tracking-wider text-gray-400">Primary Reason</th>
                  <th className="px-6 py-4 text-right"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {auditHistory.map((result, idx) => (
                  <tr key={`${result["Claim ID"]}-${idx}`} className="hover:bg-gray-50/50 transition-colors group">
                    <td className="px-6 py-4 font-black text-gray-900 text-sm whitespace-nowrap">
                      {result["Claim ID"]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`px-2 py-1 rounded-md text-[10px] font-black uppercase tracking-wider ${
                        result["Status"] === 'Approved' ? "bg-emerald-50 text-emerald-700 border border-emerald-100" :
                        result["Status"] === 'Rejected' ? "bg-rose-50 text-rose-700 border border-rose-100" :
                        "bg-amber-50 text-amber-700 border border-amber-100"
                      }`}>
                        {result["Status"]}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <ConfidenceBadge confidence={result["Confidence Score"]} />
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-500 max-w-md truncate">
                      {result["Reason"]}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <button 
                        onClick={() => handleReplay(result)}
                        className="px-4 py-2 bg-white border border-gray-200 text-gray-700 text-[11px] font-black uppercase tracking-wider rounded-lg hover:bg-gray-900 hover:text-white hover:border-gray-900 transition-all shadow-sm"
                      >
                        Replay Audit
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default AuditLogPage;
